"""empty message

Revision ID: 0ffaa3cfa1ef
Revises: 
Create Date: 2023-12-16 08:27:11.226638

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ffaa3cfa1ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Proxy',
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Proxy_id'), 'Proxy', ['id'], unique=False)
    op.create_index(op.f('ix_Proxy_ip'), 'Proxy', ['ip'], unique=False)
    # op.drop_index('ix_FaceBook_id', table_name='FaceBook')
    # op.drop_table('FaceBook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('FaceBook',
    # sa.Column('file', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('fa_secret', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('cookie', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('email_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='FaceBook_pkey')
    # )
    # op.create_index('ix_FaceBook_id', 'FaceBook', ['id'], unique=False)
    op.drop_index(op.f('ix_Proxy_ip'), table_name='Proxy')
    op.drop_index(op.f('ix_Proxy_id'), table_name='Proxy')
    op.drop_table('Proxy')
    # ### end Alembic commands ###
